name: run ui test

on: [push]

jobs: 
  ui-tests:
    runs-on: ubuntu-latest
    name: Run UI autotests
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -sv
      
